package com.app.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.dao.UserRequest;
import com.app.dao.UserResponse;
import com.app.entity.User;
import com.app.service.IUserService;
import com.app.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private IUserService service;
	
	@Autowired
	private JwtUtil jwtUtil;
	
	
	@GetMapping("/get")
	public String getMessage() {
		return "GOT THE MESSAGE ";
	}
	
	
	@PostMapping("/save")
	public ResponseEntity<String> loginUser(@RequestBody User user){
			
		Long id=service.saveUser(user);
		return ResponseEntity.ok("User saved with id "+id);
		
	}
	//this is not recommended for the production purpose method 
	@GetMapping("/all")
	public ResponseEntity<List<User>> getAllUser(){
		
		ResponseEntity<List<User>> response=null;
		try {
			List<User> list=service.getUser();
			response=ResponseEntity.ok(list);
		}catch (Exception e) {
			// TODO: handle exception
		}
		
		return response;
	}
	
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
		
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						userRequest.getUsername(),
						userRequest.getPassword())
				);
		
		
		String token=jwtUtil.generateToken(userRequest.getUsername());
		return ResponseEntity.ok(new UserResponse(token,"GENERATED BY MR.NARYAN - CHONDE"));
	}
	
	//after generation login 

	
	@GetMapping("/welcome")
	public ResponseEntity<String > getWelcome(){
		
		ResponseEntity<String > response=null;
		try {
			response=ResponseEntity.ok("WELCOME TO APP VIA LOGIN");
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return null;
	}
}
